### ISSUE TITLE
Not working after peardeck rebrand

### ISSUE THREAD

**Issue by HopsTheThird** [ading2210/edulastic-tools#3]
After the rebrand to "Peardeck", it now throws an error saying "ERROR: invalid url"

**Comment by quinny-Boy** [comment]
I tried patching the code and it didn't work.

I injected fullscreen_payload.js into the console and changed the parts that required the website URL (line 1 and 17)

It seems there have been more changes to the site than just a rebrand, because in the console I was getting messages saying "edulastic-tools allowed: [EVENT]"

This leads me to believe that the script was working as intended, but the website has changed the way it handles certain anti-cheating measures and the script was working for some measures but failing for others.

Or maybe I patched it wrong. I'm not very good at javascript so it's possible I didn't patch it right.

Hope this helps.

**Comment by ading2210** [comment]
The latest commit fixes the unreleased scores script, though I still need to fix the exit bypass.

**Comment by Vincentvhe** [comment]
Pls it's not working

**Comment by ading2210** [comment]
This has been fixed in PR #7.

**Comment by Humanbieng** [comment]
What do I paste into console with the rebrand happening for the fullscreen?
